(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
(256, 256, 3)
<class 'numpy.ndarray'>
Traceback (most recent call last):
  File "train_one_neuron_head.py", line 224, in <module>
    train_dataset.visualise()
  File "/home/myuser1/Desktop/sign-language-summer-research/experiments/seven_sees/dataset/dataset.py", line 276, in visualise
    results = self.transforms(results)
TypeError: 'NoneType' object is not callable